inherit_from: .rubocop_todo.yml

# .rubocop.yml
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "storage/**/*"
    - "public/**/*"

# Remove the Rails section - it's causing the error
# Rails:
#   Enabled: true

# Disable specific rules that are too strict for now
Layout/EndAlignment:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "config/environments/*.rb"

Style/Documentation:
  Enabled: false
